build:
  os: ubuntu-22.04
  tools:
    python: 3.7
version: 2
sphinx:
  configuration: docs/conf.py
python:
    version: 3.7
    install:
    - method: pip
      path: .
      extra_requirements:
        - docs
