version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry==1.8.3
      - poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --extras docs
mkdocs:
  configuration: mkdocs.yml
