name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files.
    paths:
      - "docs/**"

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@31a30360a2d7530806bff6855aa209167f06a89c  # latest commit on main (action deprecated, no releases)
        with:
          project-slug: "fgpyo"
